apiVersion: v1
kind: Service
metadata:
  name: "unrealserver-{{ $.Values.name }}"
  namespace: {{ $.Values.namespace }}
  labels:
    {{- include "unrealserver.labels" $ | nindent 4 }}
    service-type: active
spec:
  type: NodePort
  ports:
    - name: gameserver1
      port: 7777
      targetPort: 7777
      protocol: UDP
      nodePort: 31777
    - name: gameserver2
      port: 7778
      targetPort: 7778
      protocol: UDP
      nodePort: 31778
    - name: gameserver3
      port: 7779
      targetPort: 7779
      protocol: UDP
      nodePort: 31779
    - name: gameserver4
      port: 7780
      targetPort: 7780
      protocol: UDP
      nodePort: 31780
    - name: gameserver5
      port: 7781
      targetPort: 7781
      protocol: UDP
      nodePort: 31781
  selector:
    {{- include "unrealserver.selectorLabels" $ | nindent 4 }}
