{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: "unrealserver-{{.Values.name}}"
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "unrealserver.labels" . | nindent 4 }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
{{- end }}
