name: "unrealserver-ghs"
environmentName: "dev"
image:
  repository: "docker.galluman.com/unreal/ghs-server"
  tag: "3091105"
  pullPolicy: Always
resources:
  requests:
    cpu: 2
    memory: 4G
  limits:
    cpu: 4
    memory: 8G
serverMaps:
  map1: Airport
  map2: Airport
  map3: Airport
  map4: Airport
  map5: Airport
nodePorts:
  server1: 30777
  server2: 30778
  server3: 30779
  server4: 30780
  server5: 30781
