name: "unrealserver-ghs"
environmentName: "dev"
image:
  repository: "docker.galluman.com/unreal/ghs-server"
  tag: "3242248"
  pullPolicy: Always
resources:
  requests:
    cpu: 2
    memory: 4G
  limits:
    cpu: 4
    memory: 8G
serverMaps:
  map1: /Game/GHS/Levels/Airport/GHS_Airport.umap
  map2: /Game/GHS/Levels/AbandonedFactory/GHS_AbandonedFactory.umap
  map3: /Game/GHS/Levels/AbandonedFactory/GHS_AbandonedFactory.umap
  map4: /Game/GHS/Levels/AbandonedFactory/GHS_AbandonedFactory.umap
  map5: /Game/GHS/Levels/AbandonedFactory/GHS_AbandonedFactory.umap
nodePorts:
  server1: 30777
  server2: 30778
  server3: 30779
  server4: 30780
  server5: 30781
