name: "unrealserver-ghs"
environmentName: "dev"
image:
  repository: "docker.galluman.com/unreal/ghs-server"
  tag: "3220051"
  pullPolicy: Always
resources:
  requests:
    cpu: 2
    memory: 4G
  limits:
    cpu: 4
    memory: 8G
serverMaps:
  map1: GHS_Airport
  map2: GHS_AbandonedFactory
  map3: GHS_AbandonedFactory
  map4: GHS_AbandonedFactory
  map5: GHS_AbandonedFactory
nodePorts:
  server1: 30777
  server2: 30778
  server3: 30779
  server4: 30780
  server5: 30781
