name: "unrealserver-ghs"
environmentName: "prod"

image:
  repository: "docker.galluman.com/unreal/ghs-server"
  tag: "3072157"
  pullPolicy: Always

resources:
  requests:
    cpu: 200m
    memory: 64Mi
  limits:
    cpu: 2
    memory: 512Mi

serverMaps:
  map1: Airport
  map2: Airport
  map3: Airport
  map4: Airport
  map5: Airport

nodePorts:
  server1: 31777
  server2: 31778
  server3: 31779
  server4: 31780
  server5: 31781
