name: "unrealserver-ghs"
environmentName: "prod"

image:
  repository: "docker.galluman.com/unreal/ghs-server"
  tag: "3072157"
  pullPolicy: Always

resources:
  requests:
    cpu: 200m
    memory: 64Mi
  limits:
    cpu: 2
    memory: 512Mi

serverMaps:
  map1: /Game/GHS/Levels/Airport/GHS_Airport.GHS_Airport
  map2: /Game/GHS/Levels/AbandonedFactory/GHS_AbandonedFactory.GHS_AbandonedFactory
  map3: /Game/GHS/Levels/Airport/GHS_Airport.GHS_Airport
  map4: /Game/GHS/Levels/Airport/GHS_Airport.GHS_Airport
  map5: /Game/GHS/Levels/Airport/GHS_Airport.GHS_Airport

nodePorts:
  server1: 31777
  server2: 31778
  server3: 31779
  server4: 31780
  server5: 31781
