# Name of the release
name: ""

# Environment name for the release
environmentName: "dev"

# Number of replicas
replicaCount: 1

# Image information
image:
  repository: "docker.galluman.com/backendservice/backendNAME"
  tag: ""
  pullPolicy: IfNotPresent
  imagePullSecret: nexuspullsecret

# Create service account and mount api token for the deployment
# The name of the service account will be generated like: backendservice-$RELEASE_NAME
serviceAccount:
  create: true
  automount: false
  annotations: {}

# Resources for the pods
resources: {}
# limits:
#   cpu: 100m
#   memory: 128Mi
# requests:
#   cpu: 100m
#   memory: 128Mi

# Probes information
livenessProbe:
  initialDelaySeconds: 5
  periodSeconds: 5
  httpGet:
    path: /healthz
    port: 8080
readinessProbe:
  initialDelaySeconds: 5
  periodSeconds: 5
  httpGet:
    path: /healthz
    port: 8080
startupProbe:
  initialDelaySeconds: 5
  periodSeconds: 5
  httpGet:
    path: /healthz
    port: 8080

# Kong Gateway and HTTPRoute settings
apigateway:
  gatewayName: backend-api
  hostname: api.galluman.com
  pathPrefix: /
  cors:
    enabled: true
    spec:
      origins:
        - "*"
      methods:
        - GET
        - POST
        - PUT
        - PATCH
        - DELETE
        - OPTIONS
      headers:
        - Accept
        - Authorization
        - Content-Type
      exposed_headers:
        - X-Auth-Token
      credentials: true
      max_age: 3600
  rateLimit:
    enabled: true
    spec:
      second: 10
      minute: 500
      policy: local


# Database settings
database:
  usesDatabase: true

# Extra ENV variables
# extraEnvVars:
#   - name: VAR1
#     value: VALUE1


# Rollout Strategy
# Argo Rollouts strategy section.
# see: https://argo-rollouts.readthedocs.io/en/stable/features/specification/
rollout:
  strategy:
    blueGreen:
      autoPromotionEnabled: true

# If a blue/green rollout is used, activeService and previewService will be
# set to $NAME and $NAME-preview
#  blueGreen:
#    autoPromotionEnabled: true

# If a canary rollout is used, stable and canary services will be
# set to $NAME and $NAME-canary
#  canary:
