{{ if .Values.middleware.headers.enabled }}
kind: Middleware
apiVersion: traefik.io/v1alpha1
metadata:
  name: "backendservice-{{ .Values.name }}-headers"
  namespace: {{ .Values.environmentName }}
  labels:
    {{- include "backendservice.labels" . | nindent 4 }}
spec:
  headers:
    {{- toYaml .Values.middleware.headers.spec | nindent 4 }}
{{ end }}
