---
# Source: backendservice/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: "backendservice-server"
  namespace: dev
  labels:
    app.kubernetes.io/created-by: backendservice-helm
    app.kubernetes.io/instance: "backendservice-server"
    app.kubernetes.io/name: BackendService
    app.kubernetes.io/version: 509741c79edaf9d6117de7c7618d7a9236779cca
    lab.home/environment: dev
    app: server
    version: 509741c79edaf9d6117de7c7618d7a9236779cca
    service-type: active
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/instance: "backendservice-server"
    app.kubernetes.io/name: BackendService
---
# Source: backendservice/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: "backendservice-server-preview"
  namespace: 
  labels:
    app.kubernetes.io/created-by: backendservice-helm
    app.kubernetes.io/instance: "backendservice-server"
    app.kubernetes.io/name: BackendService
    app.kubernetes.io/version: 509741c79edaf9d6117de7c7618d7a9236779cca
    lab.home/environment: dev
    app: server
    version: 509741c79edaf9d6117de7c7618d7a9236779cca
    service-type: preview
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/instance: "backendservice-server"
    app.kubernetes.io/name: BackendService
